// Chapter icons: a curated set of Tabler icons, stored by their Tabler name (FRM-07).
import {
  IconActivity,
  IconAlertTriangle,
  IconAmbulance,
  IconApple,
  IconBabyCarriage,
  IconBandage,
  IconBed,
  IconBeer,
  IconBone,
  IconBrain,
  IconBuildingHospital,
  IconCalendar,
  IconClipboardList,
  IconDental,
  IconDna,
  IconDroplet,
  IconEar,
  IconEye,
  IconFileText,
  IconFirstAidKit,
  IconFriends,
  IconGenderFemale,
  IconGenderMale,
  IconGrain,
  IconHeart,
  IconHeartbeat,
  IconHome,
  IconLungs,
  IconMedicalCross,
  IconMicroscope,
  IconMoon,
  IconMoodSmile,
  IconNeedle,
  IconNotes,
  IconPhone,
  IconPill,
  IconRuler,
  IconRun,
  IconSalad,
  IconScale,
  IconScissors,
  IconSmoking,
  IconStethoscope,
  IconTestPipe,
  IconThermometer,
  IconUser,
  IconUsers,
  IconVaccine,
  IconVirus,
  IconWalk,
  IconWheelchair,
  IconWind,
  IconZzz,
  type Icon,
} from "@tabler/icons-react";

export const DEFAULT_CHAPTER_ICON = "file-text";

export const CHAPTER_ICONS: Record<string, Icon> = {
  "activity": IconActivity,
  "alert-triangle": IconAlertTriangle,
  "ambulance": IconAmbulance,
  "apple": IconApple,
  "baby-carriage": IconBabyCarriage,
  "bandage": IconBandage,
  "bed": IconBed,
  "beer": IconBeer,
  "bone": IconBone,
  "brain": IconBrain,
  "building-hospital": IconBuildingHospital,
  "calendar": IconCalendar,
  "clipboard-list": IconClipboardList,
  "dental": IconDental,
  "dna": IconDna,
  "droplet": IconDroplet,
  "ear": IconEar,
  "eye": IconEye,
  "file-text": IconFileText,
  "first-aid-kit": IconFirstAidKit,
  "friends": IconFriends,
  "gender-female": IconGenderFemale,
  "gender-male": IconGenderMale,
  "grain": IconGrain,
  "heart": IconHeart,
  "heartbeat": IconHeartbeat,
  "home": IconHome,
  "lungs": IconLungs,
  "medical-cross": IconMedicalCross,
  "microscope": IconMicroscope,
  "moon": IconMoon,
  "mood-smile": IconMoodSmile,
  "needle": IconNeedle,
  "notes": IconNotes,
  "phone": IconPhone,
  "pill": IconPill,
  "ruler": IconRuler,
  "run": IconRun,
  "salad": IconSalad,
  "scale": IconScale,
  "scissors": IconScissors,
  "smoking": IconSmoking,
  "stethoscope": IconStethoscope,
  "test-pipe": IconTestPipe,
  "thermometer": IconThermometer,
  "user": IconUser,
  "users": IconUsers,
  "vaccine": IconVaccine,
  "virus": IconVirus,
  "walk": IconWalk,
  "wheelchair": IconWheelchair,
  "wind": IconWind,
  "zzz": IconZzz,
};

/** The icon component for a stored name, falling back to the default. */
export const chapterIcon = (name: string): Icon => CHAPTER_ICONS[name] ?? CHAPTER_ICONS[DEFAULT_CHAPTER_ICON];
