// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chapters.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createChapter = `-- name: CreateChapter :one
INSERT INTO chapters (version_id, position, name, updated_by)
VALUES ($1, (SELECT coalesce(max(position), 0) + 1 FROM chapters WHERE version_id = $1), $2, $3)
RETURNING id
`

type CreateChapterParams struct {
	VersionID uuid.UUID `json:"versionId"`
	Name      string    `json:"name"`
	UpdatedBy uuid.UUID `json:"updatedBy"`
}

func (q *Queries) CreateChapter(ctx context.Context, arg CreateChapterParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createChapter, arg.VersionID, arg.Name, arg.UpdatedBy)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteChapter = `-- name: DeleteChapter :exec
DELETE FROM chapters WHERE id = $1
`

func (q *Queries) DeleteChapter(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChapter, id)
	return err
}

const getChapter = `-- name: GetChapter :one
SELECT c.id, c.version_id, c.position, c.name, c.description, c.icon, c.audience,
       c.content, c.revision, c.updated_at,
       v.status AS version_status, v.questionnaire_id, q.name AS questionnaire_name
FROM chapters c
JOIN questionnaire_versions v ON v.id = c.version_id
JOIN questionnaires q ON q.id = v.questionnaire_id
WHERE c.id = $1 AND q.hospital_id = $2
`

type GetChapterParams struct {
	ID         uuid.UUID `json:"id"`
	HospitalID uuid.UUID `json:"hospitalId"`
}

type GetChapterRow struct {
	ID                uuid.UUID       `json:"id"`
	VersionID         uuid.UUID       `json:"versionId"`
	Position          int32           `json:"position"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	Icon              string          `json:"icon"`
	Audience          string          `json:"audience"`
	Content           json.RawMessage `json:"content"`
	Revision          int32           `json:"revision"`
	UpdatedAt         time.Time       `json:"updatedAt"`
	VersionStatus     string          `json:"versionStatus"`
	QuestionnaireID   uuid.UUID       `json:"questionnaireId"`
	QuestionnaireName string          `json:"questionnaireName"`
}

func (q *Queries) GetChapter(ctx context.Context, arg GetChapterParams) (GetChapterRow, error) {
	row := q.db.QueryRow(ctx, getChapter, arg.ID, arg.HospitalID)
	var i GetChapterRow
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.Position,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Audience,
		&i.Content,
		&i.Revision,
		&i.UpdatedAt,
		&i.VersionStatus,
		&i.QuestionnaireID,
		&i.QuestionnaireName,
	)
	return i, err
}

const getChapterMeta = `-- name: GetChapterMeta :one
SELECT c.id, c.version_id, c.name, c.description, c.icon, c.audience, c.revision,
       v.status AS version_status, v.questionnaire_id, q.name AS questionnaire_name
FROM chapters c
JOIN questionnaire_versions v ON v.id = c.version_id
JOIN questionnaires q ON q.id = v.questionnaire_id
WHERE c.id = $1 AND q.hospital_id = $2
`

type GetChapterMetaParams struct {
	ID         uuid.UUID `json:"id"`
	HospitalID uuid.UUID `json:"hospitalId"`
}

type GetChapterMetaRow struct {
	ID                uuid.UUID `json:"id"`
	VersionID         uuid.UUID `json:"versionId"`
	Name              string    `json:"name"`
	Description       string    `json:"description"`
	Icon              string    `json:"icon"`
	Audience          string    `json:"audience"`
	Revision          int32     `json:"revision"`
	VersionStatus     string    `json:"versionStatus"`
	QuestionnaireID   uuid.UUID `json:"questionnaireId"`
	QuestionnaireName string    `json:"questionnaireName"`
}

func (q *Queries) GetChapterMeta(ctx context.Context, arg GetChapterMetaParams) (GetChapterMetaRow, error) {
	row := q.db.QueryRow(ctx, getChapterMeta, arg.ID, arg.HospitalID)
	var i GetChapterMetaRow
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Audience,
		&i.Revision,
		&i.VersionStatus,
		&i.QuestionnaireID,
		&i.QuestionnaireName,
	)
	return i, err
}

const listChapters = `-- name: ListChapters :many

SELECT c.id, c.position, c.name, c.description, c.icon, c.audience, c.revision, c.updated_at
FROM chapters c
WHERE c.version_id = $1
ORDER BY c.position, c.name
`

type ListChaptersRow struct {
	ID          uuid.UUID `json:"id"`
	Position    int32     `json:"position"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Icon        string    `json:"icon"`
	Audience    string    `json:"audience"`
	Revision    int32     `json:"revision"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// Every chapter lookup joins up to the questionnaire so it is scoped to the hospital.
func (q *Queries) ListChapters(ctx context.Context, versionID uuid.UUID) ([]ListChaptersRow, error) {
	rows, err := q.db.Query(ctx, listChapters, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChaptersRow{}
	for rows.Next() {
		var i ListChaptersRow
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Audience,
			&i.Revision,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveChapterContent = `-- name: SaveChapterContent :one
UPDATE chapters
SET content = $1, revision = revision + 1, updated_by = $2, updated_at = now()
WHERE id = $3 AND revision = $4
RETURNING revision
`

type SaveChapterContentParams struct {
	Content   json.RawMessage `json:"content"`
	UpdatedBy uuid.UUID       `json:"updatedBy"`
	ID        uuid.UUID       `json:"id"`
	Revision  int32           `json:"revision"`
}

// Saves only if nobody saved since the caller loaded `revision` (LCY-04).
func (q *Queries) SaveChapterContent(ctx context.Context, arg SaveChapterContentParams) (int32, error) {
	row := q.db.QueryRow(ctx, saveChapterContent,
		arg.Content,
		arg.UpdatedBy,
		arg.ID,
		arg.Revision,
	)
	var revision int32
	err := row.Scan(&revision)
	return revision, err
}

const setChapterPosition = `-- name: SetChapterPosition :exec
UPDATE chapters SET position = $3 WHERE id = $1 AND version_id = $2
`

type SetChapterPositionParams struct {
	ID        uuid.UUID `json:"id"`
	VersionID uuid.UUID `json:"versionId"`
	Position  int32     `json:"position"`
}

func (q *Queries) SetChapterPosition(ctx context.Context, arg SetChapterPositionParams) error {
	_, err := q.db.Exec(ctx, setChapterPosition, arg.ID, arg.VersionID, arg.Position)
	return err
}

const updateChapterMeta = `-- name: UpdateChapterMeta :exec
UPDATE chapters
SET name = $2, description = $3, icon = $4, audience = $5, updated_by = $6, updated_at = now()
WHERE id = $1
`

type UpdateChapterMetaParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Icon        string    `json:"icon"`
	Audience    string    `json:"audience"`
	UpdatedBy   uuid.UUID `json:"updatedBy"`
}

func (q *Queries) UpdateChapterMeta(ctx context.Context, arg UpdateChapterMetaParams) error {
	_, err := q.db.Exec(ctx, updateChapterMeta,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Audience,
		arg.UpdatedBy,
	)
	return err
}
