// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: codes.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listCategories = `-- name: ListCategories :many
SELECT id, name, note_only FROM categories ORDER BY note_only, name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.NoteOnly); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCodes = `-- name: SearchCodes :many
SELECT c.id, c.code_set, c.code, c.description, c.full_name, cat.name AS category_name
FROM codes c
LEFT JOIN categories cat ON cat.id = c.category_id
WHERE c.status = 'active'
  AND c.code_set = $1
  AND (c.code ILIKE $2::text || '%' OR c.description ILIKE '%' || $2::text || '%')
ORDER BY (lower(c.code) = lower($2::text)) DESC,
         (c.description ILIKE $2::text || '%') DESC,
         similarity(c.description, $2::text) DESC,
         c.description
LIMIT 20
`

type SearchCodesParams struct {
	CodeSet string `json:"codeSet"`
	Query   string `json:"query"`
}

type SearchCodesRow struct {
	ID           uuid.UUID `json:"id"`
	CodeSet      string    `json:"codeSet"`
	Code         string    `json:"code"`
	Description  string    `json:"description"`
	FullName     string    `json:"fullName"`
	CategoryName *string   `json:"categoryName"`
}

// CLN-09: part of the code or description, within one code set, active only.
// ILIKE '%…%' is served by the pg_trgm GIN indexes.
func (q *Queries) SearchCodes(ctx context.Context, arg SearchCodesParams) ([]SearchCodesRow, error) {
	rows, err := q.db.Query(ctx, searchCodes, arg.CodeSet, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchCodesRow{}
	for rows.Next() {
		var i SearchCodesRow
		if err := rows.Scan(
			&i.ID,
			&i.CodeSet,
			&i.Code,
			&i.Description,
			&i.FullName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
