// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: episodes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addEpisodeEvent = `-- name: AddEpisodeEvent :exec
INSERT INTO episode_events (episode_id, kind, text, user_id) VALUES ($1, $2, $3, $4)
`

type AddEpisodeEventParams struct {
	EpisodeID uuid.UUID     `json:"episodeId"`
	Kind      string        `json:"kind"`
	Text      string        `json:"text"`
	UserID    uuid.NullUUID `json:"userId"`
}

func (q *Queries) AddEpisodeEvent(ctx context.Context, arg AddEpisodeEventParams) error {
	_, err := q.db.Exec(ctx, addEpisodeEvent,
		arg.EpisodeID,
		arg.Kind,
		arg.Text,
		arg.UserID,
	)
	return err
}

const createEpisode = `-- name: CreateEpisode :one
INSERT INTO episodes (hospital_id, patient_id, version_id, procedure, anaesthetic, consultant, patient_token, created_by)
SELECT $1, p.id, v.id, $2, $3, $4,
       $5, $6
FROM patients p, questionnaire_versions v
JOIN questionnaires q ON q.id = v.questionnaire_id
WHERE p.id = $7 AND p.hospital_id = $1
  AND v.id = $8 AND v.status = 'published' AND q.hospital_id = $1
RETURNING id
`

type CreateEpisodeParams struct {
	HospitalID   uuid.UUID `json:"hospitalId"`
	Procedure    string    `json:"procedure"`
	Anaesthetic  string    `json:"anaesthetic"`
	Consultant   string    `json:"consultant"`
	PatientToken string    `json:"patientToken"`
	CreatedBy    uuid.UUID `json:"createdBy"`
	PatientID    uuid.UUID `json:"patientId"`
	VersionID    uuid.UUID `json:"versionId"`
}

// Creates nothing (no row) unless the patient and a published version both belong to the hospital.
func (q *Queries) CreateEpisode(ctx context.Context, arg CreateEpisodeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createEpisode,
		arg.HospitalID,
		arg.Procedure,
		arg.Anaesthetic,
		arg.Consultant,
		arg.PatientToken,
		arg.CreatedBy,
		arg.PatientID,
		arg.VersionID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createPatient = `-- name: CreatePatient :one

INSERT INTO patients (hospital_id, first_name, last_name, date_of_birth, sex, hospital_number, phone, email)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreatePatientParams struct {
	HospitalID     uuid.UUID   `json:"hospitalId"`
	FirstName      string      `json:"firstName"`
	LastName       string      `json:"lastName"`
	DateOfBirth    pgtype.Date `json:"dateOfBirth"`
	Sex            string      `json:"sex"`
	HospitalNumber string      `json:"hospitalNumber"`
	Phone          string      `json:"phone"`
	Email          string      `json:"email"`
}

// Every episode lookup is scoped to the hospital.
func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPatient,
		arg.HospitalID,
		arg.FirstName,
		arg.LastName,
		arg.DateOfBirth,
		arg.Sex,
		arg.HospitalNumber,
		arg.Phone,
		arg.Email,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getEpisode = `-- name: GetEpisode :one
SELECT e.id, e.status, e.procedure, e.anaesthetic, e.consultant, e.nurse_asa, e.anaesthetist_asa,
       e.patient_token, e.patient_submitted_at, e.review_completed_at, e.created_at, e.version_id,
       reviewer.name AS review_completed_by_name,
       p.id AS patient_id, p.first_name, p.last_name, p.date_of_birth, p.sex, p.hospital_number, p.phone, p.email,
       q.name AS questionnaire_name, v.version_no
FROM episodes e
JOIN patients p ON p.id = e.patient_id
JOIN questionnaire_versions v ON v.id = e.version_id
JOIN questionnaires q ON q.id = v.questionnaire_id
LEFT JOIN users reviewer ON reviewer.id = e.review_completed_by
WHERE e.id = $1 AND e.hospital_id = $2
`

type GetEpisodeParams struct {
	ID         uuid.UUID `json:"id"`
	HospitalID uuid.UUID `json:"hospitalId"`
}

type GetEpisodeRow struct {
	ID                    uuid.UUID          `json:"id"`
	Status                string             `json:"status"`
	Procedure             string             `json:"procedure"`
	Anaesthetic           string             `json:"anaesthetic"`
	Consultant            string             `json:"consultant"`
	NurseAsa              *int32             `json:"nurseAsa"`
	AnaesthetistAsa       *int32             `json:"anaesthetistAsa"`
	PatientToken          string             `json:"patientToken"`
	PatientSubmittedAt    pgtype.Timestamptz `json:"patientSubmittedAt"`
	ReviewCompletedAt     pgtype.Timestamptz `json:"reviewCompletedAt"`
	CreatedAt             time.Time          `json:"createdAt"`
	VersionID             uuid.UUID          `json:"versionId"`
	ReviewCompletedByName *string            `json:"reviewCompletedByName"`
	PatientID             uuid.UUID          `json:"patientId"`
	FirstName             string             `json:"firstName"`
	LastName              string             `json:"lastName"`
	DateOfBirth           pgtype.Date        `json:"dateOfBirth"`
	Sex                   string             `json:"sex"`
	HospitalNumber        string             `json:"hospitalNumber"`
	Phone                 string             `json:"phone"`
	Email                 string             `json:"email"`
	QuestionnaireName     string             `json:"questionnaireName"`
	VersionNo             int32              `json:"versionNo"`
}

func (q *Queries) GetEpisode(ctx context.Context, arg GetEpisodeParams) (GetEpisodeRow, error) {
	row := q.db.QueryRow(ctx, getEpisode, arg.ID, arg.HospitalID)
	var i GetEpisodeRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Procedure,
		&i.Anaesthetic,
		&i.Consultant,
		&i.NurseAsa,
		&i.AnaesthetistAsa,
		&i.PatientToken,
		&i.PatientSubmittedAt,
		&i.ReviewCompletedAt,
		&i.CreatedAt,
		&i.VersionID,
		&i.ReviewCompletedByName,
		&i.PatientID,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Sex,
		&i.HospitalNumber,
		&i.Phone,
		&i.Email,
		&i.QuestionnaireName,
		&i.VersionNo,
	)
	return i, err
}

const listEpisodeEvents = `-- name: ListEpisodeEvents :many
SELECT ev.id, ev.kind, ev.text, ev.created_at, u.name AS user_name
FROM episode_events ev
LEFT JOIN users u ON u.id = ev.user_id
WHERE ev.episode_id = $1
ORDER BY ev.created_at, ev.id
`

type ListEpisodeEventsRow struct {
	ID        uuid.UUID `json:"id"`
	Kind      string    `json:"kind"`
	Text      string    `json:"text"`
	CreatedAt time.Time `json:"createdAt"`
	UserName  *string   `json:"userName"`
}

func (q *Queries) ListEpisodeEvents(ctx context.Context, episodeID uuid.UUID) ([]ListEpisodeEventsRow, error) {
	rows, err := q.db.Query(ctx, listEpisodeEvents, episodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEpisodeEventsRow{}
	for rows.Next() {
		var i ListEpisodeEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Text,
			&i.CreatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodes = `-- name: ListEpisodes :many
SELECT e.id, e.status, e.procedure, e.created_at,
       p.first_name, p.last_name, p.hospital_number,
       q.name AS questionnaire_name, v.version_no
FROM episodes e
JOIN patients p ON p.id = e.patient_id
JOIN questionnaire_versions v ON v.id = e.version_id
JOIN questionnaires q ON q.id = v.questionnaire_id
WHERE e.hospital_id = $1
  AND ($2::text = '' OR e.status = $2)
ORDER BY e.created_at DESC
`

type ListEpisodesParams struct {
	HospitalID uuid.UUID `json:"hospitalId"`
	Status     string    `json:"status"`
}

type ListEpisodesRow struct {
	ID                uuid.UUID `json:"id"`
	Status            string    `json:"status"`
	Procedure         string    `json:"procedure"`
	CreatedAt         time.Time `json:"createdAt"`
	FirstName         string    `json:"firstName"`
	LastName          string    `json:"lastName"`
	HospitalNumber    string    `json:"hospitalNumber"`
	QuestionnaireName string    `json:"questionnaireName"`
	VersionNo         int32     `json:"versionNo"`
}

func (q *Queries) ListEpisodes(ctx context.Context, arg ListEpisodesParams) ([]ListEpisodesRow, error) {
	rows, err := q.db.Query(ctx, listEpisodes, arg.HospitalID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEpisodesRow{}
	for rows.Next() {
		var i ListEpisodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Procedure,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
			&i.HospitalNumber,
			&i.QuestionnaireName,
			&i.VersionNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatients = `-- name: ListPatients :many
SELECT id, first_name, last_name, date_of_birth, sex, hospital_number, phone, email
FROM patients WHERE hospital_id = $1
ORDER BY last_name, first_name
`

type ListPatientsRow struct {
	ID             uuid.UUID   `json:"id"`
	FirstName      string      `json:"firstName"`
	LastName       string      `json:"lastName"`
	DateOfBirth    pgtype.Date `json:"dateOfBirth"`
	Sex            string      `json:"sex"`
	HospitalNumber string      `json:"hospitalNumber"`
	Phone          string      `json:"phone"`
	Email          string      `json:"email"`
}

func (q *Queries) ListPatients(ctx context.Context, hospitalID uuid.UUID) ([]ListPatientsRow, error) {
	rows, err := q.db.Query(ctx, listPatients, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPatientsRow{}
	for rows.Next() {
		var i ListPatientsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.DateOfBirth,
			&i.Sex,
			&i.HospitalNumber,
			&i.Phone,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedVersions = `-- name: ListPublishedVersions :many
SELECT v.id AS version_id, v.version_no, q.name
FROM questionnaire_versions v
JOIN questionnaires q ON q.id = v.questionnaire_id
WHERE q.hospital_id = $1 AND v.status = 'published'
ORDER BY q.name
`

type ListPublishedVersionsRow struct {
	VersionID uuid.UUID `json:"versionId"`
	VersionNo int32     `json:"versionNo"`
	Name      string    `json:"name"`
}

// The HQs an episode can be given: each questionnaire's published version.
func (q *Queries) ListPublishedVersions(ctx context.Context, hospitalID uuid.UUID) ([]ListPublishedVersionsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedVersions, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedVersionsRow{}
	for rows.Next() {
		var i ListPublishedVersionsRow
		if err := rows.Scan(&i.VersionID, &i.VersionNo, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEpisode = `-- name: UpdateEpisode :exec
UPDATE episodes
SET status = $2, procedure = $3, anaesthetic = $4, consultant = $5, nurse_asa = $6, anaesthetist_asa = $7
WHERE id = $1
`

type UpdateEpisodeParams struct {
	ID              uuid.UUID `json:"id"`
	Status          string    `json:"status"`
	Procedure       string    `json:"procedure"`
	Anaesthetic     string    `json:"anaesthetic"`
	Consultant      string    `json:"consultant"`
	NurseAsa        *int32    `json:"nurseAsa"`
	AnaesthetistAsa *int32    `json:"anaesthetistAsa"`
}

func (q *Queries) UpdateEpisode(ctx context.Context, arg UpdateEpisodeParams) error {
	_, err := q.db.Exec(ctx, updateEpisode,
		arg.ID,
		arg.Status,
		arg.Procedure,
		arg.Anaesthetic,
		arg.Consultant,
		arg.NurseAsa,
		arg.AnaesthetistAsa,
	)
	return err
}
