// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: episodes.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addEpisodeEvent = `-- name: AddEpisodeEvent :exec
INSERT INTO episode_events (episode_id, kind, text, user_id) VALUES ($1, $2, $3, $4)
`

type AddEpisodeEventParams struct {
	EpisodeID uuid.UUID     `json:"episodeId"`
	Kind      string        `json:"kind"`
	Text      string        `json:"text"`
	UserID    uuid.NullUUID `json:"userId"`
}

func (q *Queries) AddEpisodeEvent(ctx context.Context, arg AddEpisodeEventParams) error {
	_, err := q.db.Exec(ctx, addEpisodeEvent,
		arg.EpisodeID,
		arg.Kind,
		arg.Text,
		arg.UserID,
	)
	return err
}

const completeReview = `-- name: CompleteReview :execrows
UPDATE episodes SET status = 'ready_for_poa', review_completed_by = $2, review_completed_at = now()
WHERE id = $1 AND status = 'ready_for_review'
`

type CompleteReviewParams struct {
	ID                uuid.UUID     `json:"id"`
	ReviewCompletedBy uuid.NullUUID `json:"reviewCompletedBy"`
}

func (q *Queries) CompleteReview(ctx context.Context, arg CompleteReviewParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeReview, arg.ID, arg.ReviewCompletedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createEpisode = `-- name: CreateEpisode :one
INSERT INTO episodes (hospital_id, patient_id, version_id, procedure, anaesthetic, consultant, created_by)
SELECT $1, p.id, v.id, $2, $3, $4,
       $5
FROM patients p, questionnaire_versions v
JOIN questionnaires q ON q.id = v.questionnaire_id
WHERE p.id = $6 AND p.hospital_id = $1
  AND v.id = $7 AND v.status = 'published' AND q.hospital_id = $1
RETURNING id
`

type CreateEpisodeParams struct {
	HospitalID  uuid.UUID `json:"hospitalId"`
	Procedure   string    `json:"procedure"`
	Anaesthetic string    `json:"anaesthetic"`
	Consultant  string    `json:"consultant"`
	CreatedBy   uuid.UUID `json:"createdBy"`
	PatientID   uuid.UUID `json:"patientId"`
	VersionID   uuid.UUID `json:"versionId"`
}

// Creates nothing (no row) unless the patient and a published version both belong to the hospital.
func (q *Queries) CreateEpisode(ctx context.Context, arg CreateEpisodeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createEpisode,
		arg.HospitalID,
		arg.Procedure,
		arg.Anaesthetic,
		arg.Consultant,
		arg.CreatedBy,
		arg.PatientID,
		arg.VersionID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createPatient = `-- name: CreatePatient :one

INSERT INTO patients (hospital_id, first_name, last_name, date_of_birth, sex, hospital_number, phone, email)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreatePatientParams struct {
	HospitalID     uuid.UUID   `json:"hospitalId"`
	FirstName      string      `json:"firstName"`
	LastName       string      `json:"lastName"`
	DateOfBirth    pgtype.Date `json:"dateOfBirth"`
	Sex            string      `json:"sex"`
	HospitalNumber string      `json:"hospitalNumber"`
	Phone          string      `json:"phone"`
	Email          string      `json:"email"`
}

// Every episode lookup is scoped to the hospital.
func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPatient,
		arg.HospitalID,
		arg.FirstName,
		arg.LastName,
		arg.DateOfBirth,
		arg.Sex,
		arg.HospitalNumber,
		arg.Phone,
		arg.Email,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getEpisode = `-- name: GetEpisode :one
SELECT e.id, e.status, e.procedure, e.anaesthetic, e.consultant, e.nurse_asa, e.anaesthetist_asa,
       e.patient_submitted_at, e.review_completed_at, e.created_at, e.version_id,
       reviewer.name AS review_completed_by_name,
       p.id AS patient_id, p.first_name, p.last_name, p.date_of_birth, p.sex, p.hospital_number, p.phone, p.email,
       q.name AS questionnaire_name, v.version_no
FROM episodes e
JOIN patients p ON p.id = e.patient_id
JOIN questionnaire_versions v ON v.id = e.version_id
JOIN questionnaires q ON q.id = v.questionnaire_id
LEFT JOIN users reviewer ON reviewer.id = e.review_completed_by
WHERE e.id = $1 AND e.hospital_id = $2
`

type GetEpisodeParams struct {
	ID         uuid.UUID `json:"id"`
	HospitalID uuid.UUID `json:"hospitalId"`
}

type GetEpisodeRow struct {
	ID                    uuid.UUID          `json:"id"`
	Status                string             `json:"status"`
	Procedure             string             `json:"procedure"`
	Anaesthetic           string             `json:"anaesthetic"`
	Consultant            string             `json:"consultant"`
	NurseAsa              *int32             `json:"nurseAsa"`
	AnaesthetistAsa       *int32             `json:"anaesthetistAsa"`
	PatientSubmittedAt    pgtype.Timestamptz `json:"patientSubmittedAt"`
	ReviewCompletedAt     pgtype.Timestamptz `json:"reviewCompletedAt"`
	CreatedAt             time.Time          `json:"createdAt"`
	VersionID             uuid.UUID          `json:"versionId"`
	ReviewCompletedByName *string            `json:"reviewCompletedByName"`
	PatientID             uuid.UUID          `json:"patientId"`
	FirstName             string             `json:"firstName"`
	LastName              string             `json:"lastName"`
	DateOfBirth           pgtype.Date        `json:"dateOfBirth"`
	Sex                   string             `json:"sex"`
	HospitalNumber        string             `json:"hospitalNumber"`
	Phone                 string             `json:"phone"`
	Email                 string             `json:"email"`
	QuestionnaireName     string             `json:"questionnaireName"`
	VersionNo             int32              `json:"versionNo"`
}

func (q *Queries) GetEpisode(ctx context.Context, arg GetEpisodeParams) (GetEpisodeRow, error) {
	row := q.db.QueryRow(ctx, getEpisode, arg.ID, arg.HospitalID)
	var i GetEpisodeRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Procedure,
		&i.Anaesthetic,
		&i.Consultant,
		&i.NurseAsa,
		&i.AnaesthetistAsa,
		&i.PatientSubmittedAt,
		&i.ReviewCompletedAt,
		&i.CreatedAt,
		&i.VersionID,
		&i.ReviewCompletedByName,
		&i.PatientID,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Sex,
		&i.HospitalNumber,
		&i.Phone,
		&i.Email,
		&i.QuestionnaireName,
		&i.VersionNo,
	)
	return i, err
}

const getPatientEpisode = `-- name: GetPatientEpisode :one
SELECT e.id, e.status, e.patient_submitted_at, e.version_id,
       p.first_name, p.last_name, p.date_of_birth, p.sex,
       q.name AS questionnaire_name
FROM episodes e
JOIN patients p ON p.id = e.patient_id
JOIN questionnaire_versions v ON v.id = e.version_id
JOIN questionnaires q ON q.id = v.questionnaire_id
WHERE e.id = $1
`

type GetPatientEpisodeRow struct {
	ID                 uuid.UUID          `json:"id"`
	Status             string             `json:"status"`
	PatientSubmittedAt pgtype.Timestamptz `json:"patientSubmittedAt"`
	VersionID          uuid.UUID          `json:"versionId"`
	FirstName          string             `json:"firstName"`
	LastName           string             `json:"lastName"`
	DateOfBirth        pgtype.Date        `json:"dateOfBirth"`
	Sex                string             `json:"sex"`
	QuestionnaireName  string             `json:"questionnaireName"`
}

// The episode of a signed-in patient (their session names it).
func (q *Queries) GetPatientEpisode(ctx context.Context, id uuid.UUID) (GetPatientEpisodeRow, error) {
	row := q.db.QueryRow(ctx, getPatientEpisode, id)
	var i GetPatientEpisodeRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.PatientSubmittedAt,
		&i.VersionID,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Sex,
		&i.QuestionnaireName,
	)
	return i, err
}

const getVersionChapter = `-- name: GetVersionChapter :one
SELECT id, audience, content FROM chapters WHERE id = $1 AND version_id = $2
`

type GetVersionChapterParams struct {
	ID        uuid.UUID `json:"id"`
	VersionID uuid.UUID `json:"versionId"`
}

type GetVersionChapterRow struct {
	ID       uuid.UUID       `json:"id"`
	Audience string          `json:"audience"`
	Content  json.RawMessage `json:"content"`
}

func (q *Queries) GetVersionChapter(ctx context.Context, arg GetVersionChapterParams) (GetVersionChapterRow, error) {
	row := q.db.QueryRow(ctx, getVersionChapter, arg.ID, arg.VersionID)
	var i GetVersionChapterRow
	err := row.Scan(&i.ID, &i.Audience, &i.Content)
	return i, err
}

const listEpisodeAnswers = `-- name: ListEpisodeAnswers :many
SELECT a.chapter_id, a.actor, a.data, a.updated_at, a.validated_at, u.name AS updated_by_name
FROM episode_answers a
LEFT JOIN users u ON u.id = a.updated_by
WHERE a.episode_id = $1
`

type ListEpisodeAnswersRow struct {
	ChapterID     uuid.UUID          `json:"chapterId"`
	Actor         string             `json:"actor"`
	Data          json.RawMessage    `json:"data"`
	UpdatedAt     time.Time          `json:"updatedAt"`
	ValidatedAt   pgtype.Timestamptz `json:"validatedAt"`
	UpdatedByName *string            `json:"updatedByName"`
}

func (q *Queries) ListEpisodeAnswers(ctx context.Context, episodeID uuid.UUID) ([]ListEpisodeAnswersRow, error) {
	rows, err := q.db.Query(ctx, listEpisodeAnswers, episodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEpisodeAnswersRow{}
	for rows.Next() {
		var i ListEpisodeAnswersRow
		if err := rows.Scan(
			&i.ChapterID,
			&i.Actor,
			&i.Data,
			&i.UpdatedAt,
			&i.ValidatedAt,
			&i.UpdatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodeEvents = `-- name: ListEpisodeEvents :many
SELECT ev.id, ev.kind, ev.text, ev.created_at, u.name AS user_name
FROM episode_events ev
LEFT JOIN users u ON u.id = ev.user_id
WHERE ev.episode_id = $1
ORDER BY ev.created_at, ev.id
`

type ListEpisodeEventsRow struct {
	ID        uuid.UUID `json:"id"`
	Kind      string    `json:"kind"`
	Text      string    `json:"text"`
	CreatedAt time.Time `json:"createdAt"`
	UserName  *string   `json:"userName"`
}

func (q *Queries) ListEpisodeEvents(ctx context.Context, episodeID uuid.UUID) ([]ListEpisodeEventsRow, error) {
	rows, err := q.db.Query(ctx, listEpisodeEvents, episodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEpisodeEventsRow{}
	for rows.Next() {
		var i ListEpisodeEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Text,
			&i.CreatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodes = `-- name: ListEpisodes :many
SELECT e.id, e.status, e.procedure, e.created_at,
       p.first_name, p.last_name, p.hospital_number,
       q.name AS questionnaire_name, v.version_no
FROM episodes e
JOIN patients p ON p.id = e.patient_id
JOIN questionnaire_versions v ON v.id = e.version_id
JOIN questionnaires q ON q.id = v.questionnaire_id
WHERE e.hospital_id = $1
  AND ($2::text = '' OR e.status = $2)
ORDER BY e.created_at DESC
`

type ListEpisodesParams struct {
	HospitalID uuid.UUID `json:"hospitalId"`
	Status     string    `json:"status"`
}

type ListEpisodesRow struct {
	ID                uuid.UUID `json:"id"`
	Status            string    `json:"status"`
	Procedure         string    `json:"procedure"`
	CreatedAt         time.Time `json:"createdAt"`
	FirstName         string    `json:"firstName"`
	LastName          string    `json:"lastName"`
	HospitalNumber    string    `json:"hospitalNumber"`
	QuestionnaireName string    `json:"questionnaireName"`
	VersionNo         int32     `json:"versionNo"`
}

func (q *Queries) ListEpisodes(ctx context.Context, arg ListEpisodesParams) ([]ListEpisodesRow, error) {
	rows, err := q.db.Query(ctx, listEpisodes, arg.HospitalID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEpisodesRow{}
	for rows.Next() {
		var i ListEpisodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Procedure,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
			&i.HospitalNumber,
			&i.QuestionnaireName,
			&i.VersionNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatients = `-- name: ListPatients :many
SELECT id, first_name, last_name, date_of_birth, sex, hospital_number, phone, email
FROM patients WHERE hospital_id = $1
ORDER BY last_name, first_name
`

type ListPatientsRow struct {
	ID             uuid.UUID   `json:"id"`
	FirstName      string      `json:"firstName"`
	LastName       string      `json:"lastName"`
	DateOfBirth    pgtype.Date `json:"dateOfBirth"`
	Sex            string      `json:"sex"`
	HospitalNumber string      `json:"hospitalNumber"`
	Phone          string      `json:"phone"`
	Email          string      `json:"email"`
}

func (q *Queries) ListPatients(ctx context.Context, hospitalID uuid.UUID) ([]ListPatientsRow, error) {
	rows, err := q.db.Query(ctx, listPatients, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPatientsRow{}
	for rows.Next() {
		var i ListPatientsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.DateOfBirth,
			&i.Sex,
			&i.HospitalNumber,
			&i.Phone,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedVersions = `-- name: ListPublishedVersions :many
SELECT v.id AS version_id, v.version_no, q.name
FROM questionnaire_versions v
JOIN questionnaires q ON q.id = v.questionnaire_id
WHERE q.hospital_id = $1 AND v.status = 'published'
ORDER BY q.name
`

type ListPublishedVersionsRow struct {
	VersionID uuid.UUID `json:"versionId"`
	VersionNo int32     `json:"versionNo"`
	Name      string    `json:"name"`
}

// The HQs an episode can be given: each questionnaire's published version.
func (q *Queries) ListPublishedVersions(ctx context.Context, hospitalID uuid.UUID) ([]ListPublishedVersionsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedVersions, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedVersionsRow{}
	for rows.Next() {
		var i ListPublishedVersionsRow
		if err := rows.Scan(&i.VersionID, &i.VersionNo, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionChapters = `-- name: ListVersionChapters :many
SELECT id, name, description, icon, audience, content
FROM chapters WHERE version_id = $1
ORDER BY position, name
`

type ListVersionChaptersRow struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Icon        string          `json:"icon"`
	Audience    string          `json:"audience"`
	Content     json.RawMessage `json:"content"`
}

func (q *Queries) ListVersionChapters(ctx context.Context, versionID uuid.UUID) ([]ListVersionChaptersRow, error) {
	rows, err := q.db.Query(ctx, listVersionChapters, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVersionChaptersRow{}
	for rows.Next() {
		var i ListVersionChaptersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Audience,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveClinicianAnswers = `-- name: SaveClinicianAnswers :execrows
INSERT INTO episode_answers (episode_id, chapter_id, actor, data, updated_by, validated_at)
SELECT e.id, $1, 'clinician', $2, $3,
       CASE WHEN $4::boolean THEN now() END
FROM episodes e WHERE e.id = $5 AND e.status = 'ready_for_review'
ON CONFLICT (episode_id, chapter_id, actor) DO UPDATE
SET data = EXCLUDED.data, updated_by = EXCLUDED.updated_by, updated_at = now(), validated_at = EXCLUDED.validated_at
`

type SaveClinicianAnswersParams struct {
	ChapterID uuid.UUID       `json:"chapterId"`
	Data      json.RawMessage `json:"data"`
	UpdatedBy uuid.NullUUID   `json:"updatedBy"`
	Validated bool            `json:"validated"`
	EpisodeID uuid.UUID       `json:"episodeId"`
}

// The clinician's copy of a Question Set's answers, which is final. `validated` stamps it
// ("Validated by … on …"); a later save without it clears the stamp. Saves nothing unless the
// episode is Ready for review: before that the patient is still filling in, after it the review is complete.
func (q *Queries) SaveClinicianAnswers(ctx context.Context, arg SaveClinicianAnswersParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveClinicianAnswers,
		arg.ChapterID,
		arg.Data,
		arg.UpdatedBy,
		arg.Validated,
		arg.EpisodeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const savePatientAnswers = `-- name: SavePatientAnswers :execrows
INSERT INTO episode_answers (episode_id, chapter_id, actor, data)
SELECT e.id, $1, 'patient', $2
FROM episodes e WHERE e.id = $3 AND e.patient_submitted_at IS NULL
ON CONFLICT (episode_id, chapter_id, actor) DO UPDATE SET data = EXCLUDED.data, updated_at = now()
`

type SavePatientAnswersParams struct {
	ChapterID uuid.UUID       `json:"chapterId"`
	Data      json.RawMessage `json:"data"`
	EpisodeID uuid.UUID       `json:"episodeId"`
}

// Saves nothing once the patient has submitted: their answers are then frozen.
func (q *Queries) SavePatientAnswers(ctx context.Context, arg SavePatientAnswersParams) (int64, error) {
	result, err := q.db.Exec(ctx, savePatientAnswers, arg.ChapterID, arg.Data, arg.EpisodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const submitPatientHQ = `-- name: SubmitPatientHQ :execrows
UPDATE episodes SET patient_submitted_at = now(), status = 'ready_for_review'
WHERE id = $1 AND patient_submitted_at IS NULL
`

func (q *Queries) SubmitPatientHQ(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, submitPatientHQ, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEpisode = `-- name: UpdateEpisode :exec
UPDATE episodes
SET status = $2, procedure = $3, anaesthetic = $4, consultant = $5, nurse_asa = $6, anaesthetist_asa = $7
WHERE id = $1
`

type UpdateEpisodeParams struct {
	ID              uuid.UUID `json:"id"`
	Status          string    `json:"status"`
	Procedure       string    `json:"procedure"`
	Anaesthetic     string    `json:"anaesthetic"`
	Consultant      string    `json:"consultant"`
	NurseAsa        *int32    `json:"nurseAsa"`
	AnaesthetistAsa *int32    `json:"anaesthetistAsa"`
}

func (q *Queries) UpdateEpisode(ctx context.Context, arg UpdateEpisodeParams) error {
	_, err := q.db.Exec(ctx, updateEpisode,
		arg.ID,
		arg.Status,
		arg.Procedure,
		arg.Anaesthetic,
		arg.Consultant,
		arg.NurseAsa,
		arg.AnaesthetistAsa,
	)
	return err
}
