// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLoginLink = `-- name: CreateLoginLink :exec
INSERT INTO login_links (token_hash, token_sealed, episode_id) VALUES ($1, $2, $3)
`

type CreateLoginLinkParams struct {
	TokenHash   []byte    `json:"tokenHash"`
	TokenSealed []byte    `json:"tokenSealed"`
	EpisodeID   uuid.UUID `json:"episodeId"`
}

func (q *Queries) CreateLoginLink(ctx context.Context, arg CreateLoginLinkParams) error {
	_, err := q.db.Exec(ctx, createLoginLink, arg.TokenHash, arg.TokenSealed, arg.EpisodeID)
	return err
}

const deleteEpisodeLinks = `-- name: DeleteEpisodeLinks :exec
DELETE FROM login_links WHERE episode_id = $1
`

func (q *Queries) DeleteEpisodeLinks(ctx context.Context, episodeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEpisodeLinks, episodeID)
	return err
}

const getEpisodeLinkSealed = `-- name: GetEpisodeLinkSealed :one
SELECT token_sealed FROM login_links WHERE episode_id = $1 ORDER BY created_at DESC LIMIT 1
`

// The newest link of an episode, sealed (NULL when made before sealing).
func (q *Queries) GetEpisodeLinkSealed(ctx context.Context, episodeID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getEpisodeLinkSealed, episodeID)
	var token_sealed []byte
	err := row.Scan(&token_sealed)
	return token_sealed, err
}

const getLoginLink = `-- name: GetLoginLink :one
SELECT l.id, l.episode_id, l.locked_at, p.date_of_birth
FROM login_links l
JOIN episodes e ON e.id = l.episode_id
JOIN patients p ON p.id = e.patient_id
WHERE l.token_hash = $1
`

type GetLoginLinkRow struct {
	ID          uuid.UUID          `json:"id"`
	EpisodeID   uuid.UUID          `json:"episodeId"`
	LockedAt    pgtype.Timestamptz `json:"lockedAt"`
	DateOfBirth pgtype.Date        `json:"dateOfBirth"`
}

// A patient link by its hash, with the date of birth it must be confirmed with.
func (q *Queries) GetLoginLink(ctx context.Context, tokenHash []byte) (GetLoginLinkRow, error) {
	row := q.db.QueryRow(ctx, getLoginLink, tokenHash)
	var i GetLoginLinkRow
	err := row.Scan(
		&i.ID,
		&i.EpisodeID,
		&i.LockedAt,
		&i.DateOfBirth,
	)
	return i, err
}

const recordWrongDateOfBirth = `-- name: RecordWrongDateOfBirth :one
UPDATE login_links
SET failed_dob_attempts = failed_dob_attempts + 1,
    locked_at = CASE WHEN failed_dob_attempts + 1 >= $1::int THEN now() END
WHERE id = $2 AND locked_at IS NULL
RETURNING (locked_at IS NOT NULL)::boolean AS locked
`

type RecordWrongDateOfBirthParams struct {
	MaxAttempts int32     `json:"maxAttempts"`
	ID          uuid.UUID `json:"id"`
}

// Counts a wrong date of birth and locks the link at @max_attempts. Atomic, so tries sent in
// parallel can't get past the limit.
func (q *Queries) RecordWrongDateOfBirth(ctx context.Context, arg RecordWrongDateOfBirthParams) (bool, error) {
	row := q.db.QueryRow(ctx, recordWrongDateOfBirth, arg.MaxAttempts, arg.ID)
	var locked bool
	err := row.Scan(&locked)
	return locked, err
}

const resetDateOfBirthTries = `-- name: ResetDateOfBirthTries :exec
UPDATE login_links SET failed_dob_attempts = 0 WHERE id = $1
`

func (q *Queries) ResetDateOfBirthTries(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetDateOfBirthTries, id)
	return err
}
