// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Category struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	NoteOnly bool      `json:"noteOnly"`
}

type Chapter struct {
	ID          uuid.UUID       `json:"id"`
	VersionID   uuid.UUID       `json:"versionId"`
	Position    int32           `json:"position"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Icon        string          `json:"icon"`
	Audience    string          `json:"audience"`
	Content     json.RawMessage `json:"content"`
	Revision    int32           `json:"revision"`
	UpdatedBy   uuid.UUID       `json:"updatedBy"`
	UpdatedAt   time.Time       `json:"updatedAt"`
}

type Code struct {
	ID          uuid.UUID     `json:"id"`
	CodeSet     string        `json:"codeSet"`
	Code        string        `json:"code"`
	Description string        `json:"description"`
	FullName    string        `json:"fullName"`
	CategoryID  uuid.NullUUID `json:"categoryId"`
	Billable    bool          `json:"billable"`
	Status      string        `json:"status"`
}

type Hospital struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type Membership struct {
	UserID     uuid.UUID `json:"userId"`
	HospitalID uuid.UUID `json:"hospitalId"`
	Role       string    `json:"role"`
}

type Questionnaire struct {
	ID          uuid.UUID `json:"id"`
	HospitalID  uuid.UUID `json:"hospitalId"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedBy   uuid.UUID `json:"createdBy"`
	CreatedAt   time.Time `json:"createdAt"`
}

type QuestionnaireVersion struct {
	ID              uuid.UUID `json:"id"`
	QuestionnaireID uuid.UUID `json:"questionnaireId"`
	VersionNo       int32     `json:"versionNo"`
	Status          string    `json:"status"`
	UpdatedBy       uuid.UUID `json:"updatedBy"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

type User struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Email string    `json:"email"`
}
