// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	NoteOnly bool      `json:"noteOnly"`
}

type Chapter struct {
	ID          uuid.UUID       `json:"id"`
	VersionID   uuid.UUID       `json:"versionId"`
	Position    int32           `json:"position"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Icon        string          `json:"icon"`
	Audience    string          `json:"audience"`
	Content     json.RawMessage `json:"content"`
	Revision    int32           `json:"revision"`
	UpdatedBy   uuid.UUID       `json:"updatedBy"`
	UpdatedAt   time.Time       `json:"updatedAt"`
}

type Code struct {
	ID          uuid.UUID     `json:"id"`
	CodeSet     string        `json:"codeSet"`
	Code        string        `json:"code"`
	Description string        `json:"description"`
	FullName    string        `json:"fullName"`
	CategoryID  uuid.NullUUID `json:"categoryId"`
	Billable    bool          `json:"billable"`
	Status      string        `json:"status"`
}

type Episode struct {
	ID                 uuid.UUID          `json:"id"`
	HospitalID         uuid.UUID          `json:"hospitalId"`
	PatientID          uuid.UUID          `json:"patientId"`
	VersionID          uuid.UUID          `json:"versionId"`
	Status             string             `json:"status"`
	Procedure          string             `json:"procedure"`
	Anaesthetic        string             `json:"anaesthetic"`
	Consultant         string             `json:"consultant"`
	NurseAsa           *int32             `json:"nurseAsa"`
	AnaesthetistAsa    *int32             `json:"anaesthetistAsa"`
	PatientToken       string             `json:"patientToken"`
	PatientSubmittedAt pgtype.Timestamptz `json:"patientSubmittedAt"`
	ReviewCompletedBy  uuid.NullUUID      `json:"reviewCompletedBy"`
	ReviewCompletedAt  pgtype.Timestamptz `json:"reviewCompletedAt"`
	CreatedBy          uuid.UUID          `json:"createdBy"`
	CreatedAt          time.Time          `json:"createdAt"`
}

type EpisodeAnswer struct {
	EpisodeID   uuid.UUID          `json:"episodeId"`
	ChapterID   uuid.UUID          `json:"chapterId"`
	Actor       string             `json:"actor"`
	Data        json.RawMessage    `json:"data"`
	UpdatedBy   uuid.NullUUID      `json:"updatedBy"`
	UpdatedAt   time.Time          `json:"updatedAt"`
	ValidatedAt pgtype.Timestamptz `json:"validatedAt"`
}

type EpisodeEvent struct {
	ID        uuid.UUID     `json:"id"`
	EpisodeID uuid.UUID     `json:"episodeId"`
	Kind      string        `json:"kind"`
	Text      string        `json:"text"`
	UserID    uuid.NullUUID `json:"userId"`
	CreatedAt time.Time     `json:"createdAt"`
}

type Hospital struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type Membership struct {
	UserID     uuid.UUID `json:"userId"`
	HospitalID uuid.UUID `json:"hospitalId"`
	Role       string    `json:"role"`
}

type OptionList struct {
	ID         uuid.UUID       `json:"id"`
	HospitalID uuid.UUID       `json:"hospitalId"`
	Name       string          `json:"name"`
	Options    json.RawMessage `json:"options"`
	UpdatedBy  uuid.UUID       `json:"updatedBy"`
	UpdatedAt  time.Time       `json:"updatedAt"`
}

type Patient struct {
	ID             uuid.UUID   `json:"id"`
	HospitalID     uuid.UUID   `json:"hospitalId"`
	FirstName      string      `json:"firstName"`
	LastName       string      `json:"lastName"`
	DateOfBirth    pgtype.Date `json:"dateOfBirth"`
	Sex            string      `json:"sex"`
	HospitalNumber string      `json:"hospitalNumber"`
	Phone          string      `json:"phone"`
	Email          string      `json:"email"`
}

type Questionnaire struct {
	ID          uuid.UUID `json:"id"`
	HospitalID  uuid.UUID `json:"hospitalId"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedBy   uuid.UUID `json:"createdBy"`
	CreatedAt   time.Time `json:"createdAt"`
}

type QuestionnaireVersion struct {
	ID              uuid.UUID `json:"id"`
	QuestionnaireID uuid.UUID `json:"questionnaireId"`
	VersionNo       int32     `json:"versionNo"`
	Status          string    `json:"status"`
	UpdatedBy       uuid.UUID `json:"updatedBy"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

type User struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Email string    `json:"email"`
}
