// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: option_lists.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createOptionList = `-- name: CreateOptionList :one
INSERT INTO option_lists (hospital_id, name, options, updated_by)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateOptionListParams struct {
	HospitalID uuid.UUID       `json:"hospitalId"`
	Name       string          `json:"name"`
	Options    json.RawMessage `json:"options"`
	UpdatedBy  uuid.UUID       `json:"updatedBy"`
}

func (q *Queries) CreateOptionList(ctx context.Context, arg CreateOptionListParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createOptionList,
		arg.HospitalID,
		arg.Name,
		arg.Options,
		arg.UpdatedBy,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteOptionList = `-- name: DeleteOptionList :execrows
DELETE FROM option_lists WHERE id = $1 AND hospital_id = $2
`

type DeleteOptionListParams struct {
	ID         uuid.UUID `json:"id"`
	HospitalID uuid.UUID `json:"hospitalId"`
}

func (q *Queries) DeleteOptionList(ctx context.Context, arg DeleteOptionListParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOptionList, arg.ID, arg.HospitalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listOptionLists = `-- name: ListOptionLists :many

SELECT l.id, l.name, l.options, l.updated_at, u.name AS updated_by_name
FROM option_lists l
JOIN users u ON u.id = l.updated_by
WHERE l.hospital_id = $1
ORDER BY lower(l.name)
`

type ListOptionListsRow struct {
	ID            uuid.UUID       `json:"id"`
	Name          string          `json:"name"`
	Options       json.RawMessage `json:"options"`
	UpdatedAt     time.Time       `json:"updatedAt"`
	UpdatedByName string          `json:"updatedByName"`
}

// Option lists are scoped to a hospital (OPT-07, TEN-01).
func (q *Queries) ListOptionLists(ctx context.Context, hospitalID uuid.UUID) ([]ListOptionListsRow, error) {
	rows, err := q.db.Query(ctx, listOptionLists, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOptionListsRow{}
	for rows.Next() {
		var i ListOptionListsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Options,
			&i.UpdatedAt,
			&i.UpdatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOptionList = `-- name: UpdateOptionList :execrows
UPDATE option_lists
SET name = $3, options = $4, updated_by = $5, updated_at = now()
WHERE id = $1 AND hospital_id = $2
`

type UpdateOptionListParams struct {
	ID         uuid.UUID       `json:"id"`
	HospitalID uuid.UUID       `json:"hospitalId"`
	Name       string          `json:"name"`
	Options    json.RawMessage `json:"options"`
	UpdatedBy  uuid.UUID       `json:"updatedBy"`
}

func (q *Queries) UpdateOptionList(ctx context.Context, arg UpdateOptionListParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOptionList,
		arg.ID,
		arg.HospitalID,
		arg.Name,
		arg.Options,
		arg.UpdatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
