// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateChapter(ctx context.Context, arg CreateChapterParams) (uuid.UUID, error)
	CreateQuestionnaire(ctx context.Context, arg CreateQuestionnaireParams) (uuid.UUID, error)
	CreateVersion(ctx context.Context, arg CreateVersionParams) (uuid.UUID, error)
	DeleteChapter(ctx context.Context, id uuid.UUID) error
	DeleteQuestionnaire(ctx context.Context, arg DeleteQuestionnaireParams) error
	DraftNameExists(ctx context.Context, arg DraftNameExistsParams) (bool, error)
	GetChapter(ctx context.Context, arg GetChapterParams) (GetChapterRow, error)
	GetChapterMeta(ctx context.Context, arg GetChapterMetaParams) (GetChapterMetaRow, error)
	GetQuestionnaire(ctx context.Context, arg GetQuestionnaireParams) (GetQuestionnaireRow, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	HasNonDraftVersion(ctx context.Context, questionnaireID uuid.UUID) (bool, error)
	ListCategories(ctx context.Context) ([]Category, error)
	// Every chapter lookup joins up to the questionnaire so it is scoped to the hospital.
	ListChapters(ctx context.Context, versionID uuid.UUID) ([]ListChaptersRow, error)
	ListMemberships(ctx context.Context, userID uuid.UUID) ([]ListMembershipsRow, error)
	// The slice has one version per questionnaire, so "latest version" is that draft.
	ListQuestionnaires(ctx context.Context, arg ListQuestionnairesParams) ([]ListQuestionnairesRow, error)
	ListRolesInHospital(ctx context.Context, arg ListRolesInHospitalParams) ([]string, error)
	ListUsers(ctx context.Context) ([]User, error)
	// Serialises creates in one hospital so the unique-draft-name check can't race.
	LockHospitalQuestionnaires(ctx context.Context, hospitalID uuid.UUID) error
	Ping(ctx context.Context) (int32, error)
	// Saves only if nobody saved since the caller loaded `revision` (LCY-04).
	SaveChapterContent(ctx context.Context, arg SaveChapterContentParams) (int32, error)
	// CLN-09: part of the code or description, within one code set, active only.
	// ILIKE '%…%' is served by the pg_trgm GIN indexes.
	SearchCodes(ctx context.Context, arg SearchCodesParams) ([]SearchCodesRow, error)
	SetChapterPosition(ctx context.Context, arg SetChapterPositionParams) error
	TouchVersion(ctx context.Context, arg TouchVersionParams) error
	UpdateChapterMeta(ctx context.Context, arg UpdateChapterMetaParams) error
}

var _ Querier = (*Queries)(nil)
