// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: questionnaires.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createNextVersion = `-- name: CreateNextVersion :one
WITH v AS (
    INSERT INTO questionnaire_versions (questionnaire_id, version_no, status, updated_by)
    SELECT prev.questionnaire_id, prev.version_no + 1, 'draft', $1
    FROM questionnaire_versions prev WHERE prev.id = $2
    RETURNING questionnaire_versions.id
), c AS (
    INSERT INTO chapters (version_id, position, name, description, icon, audience, content, updated_by)
    SELECT v.id, ch.position, ch.name, ch.description, ch.icon, ch.audience, ch.content, $1
    FROM chapters ch, v
    WHERE ch.version_id = $2
)
SELECT id FROM v
`

type CreateNextVersionParams struct {
	UpdatedBy     uuid.UUID `json:"updatedBy"`
	FromVersionID uuid.UUID `json:"fromVersionId"`
}

// A new draft copied from version `from_version_id` (LCY-06/07): same chapters, same content,
// so stable IDs and test cases carry over. Chapters get new row ids.
func (q *Queries) CreateNextVersion(ctx context.Context, arg CreateNextVersionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createNextVersion, arg.UpdatedBy, arg.FromVersionID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createQuestionnaire = `-- name: CreateQuestionnaire :one
INSERT INTO questionnaires (hospital_id, name, description, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateQuestionnaireParams struct {
	HospitalID  uuid.UUID `json:"hospitalId"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedBy   uuid.UUID `json:"createdBy"`
}

func (q *Queries) CreateQuestionnaire(ctx context.Context, arg CreateQuestionnaireParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createQuestionnaire,
		arg.HospitalID,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createVersion = `-- name: CreateVersion :one
INSERT INTO questionnaire_versions (questionnaire_id, version_no, status, updated_by)
VALUES ($1, $2, 'draft', $3)
RETURNING id
`

type CreateVersionParams struct {
	QuestionnaireID uuid.UUID `json:"questionnaireId"`
	VersionNo       int32     `json:"versionNo"`
	UpdatedBy       uuid.UUID `json:"updatedBy"`
}

func (q *Queries) CreateVersion(ctx context.Context, arg CreateVersionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createVersion, arg.QuestionnaireID, arg.VersionNo, arg.UpdatedBy)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteQuestionnaire = `-- name: DeleteQuestionnaire :exec
DELETE FROM questionnaires WHERE id = $1 AND hospital_id = $2
`

type DeleteQuestionnaireParams struct {
	ID         uuid.UUID `json:"id"`
	HospitalID uuid.UUID `json:"hospitalId"`
}

func (q *Queries) DeleteQuestionnaire(ctx context.Context, arg DeleteQuestionnaireParams) error {
	_, err := q.db.Exec(ctx, deleteQuestionnaire, arg.ID, arg.HospitalID)
	return err
}

const draftNameExists = `-- name: DraftNameExists :one
SELECT EXISTS (
    SELECT 1 FROM questionnaires q
    JOIN questionnaire_versions v ON v.questionnaire_id = q.id
    WHERE q.hospital_id = $1
      AND v.status = 'draft'
      AND lower(q.name) = lower($2)
      AND q.id <> $3
)
`

type DraftNameExistsParams struct {
	HospitalID uuid.UUID `json:"hospitalId"`
	Name       string    `json:"name"`
	ExcludeID  uuid.UUID `json:"excludeId"`
}

func (q *Queries) DraftNameExists(ctx context.Context, arg DraftNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, draftNameExists, arg.HospitalID, arg.Name, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getQuestionnaire = `-- name: GetQuestionnaire :one
SELECT q.id, q.hospital_id, q.name, q.description, q.created_by, q.created_at,
       v.id AS version_id, v.version_no, v.status, v.updated_at,
       editor.name AS updated_by_name
FROM questionnaires q
JOIN LATERAL (
    SELECT id, questionnaire_id, version_no, status, updated_by, updated_at FROM questionnaire_versions qv
    WHERE qv.questionnaire_id = q.id
    ORDER BY qv.version_no DESC LIMIT 1
) v ON true
JOIN users editor ON editor.id = v.updated_by
WHERE q.id = $1 AND q.hospital_id = $2
`

type GetQuestionnaireParams struct {
	ID         uuid.UUID `json:"id"`
	HospitalID uuid.UUID `json:"hospitalId"`
}

type GetQuestionnaireRow struct {
	ID            uuid.UUID `json:"id"`
	HospitalID    uuid.UUID `json:"hospitalId"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	CreatedBy     uuid.UUID `json:"createdBy"`
	CreatedAt     time.Time `json:"createdAt"`
	VersionID     uuid.UUID `json:"versionId"`
	VersionNo     int32     `json:"versionNo"`
	Status        string    `json:"status"`
	UpdatedAt     time.Time `json:"updatedAt"`
	UpdatedByName string    `json:"updatedByName"`
}

func (q *Queries) GetQuestionnaire(ctx context.Context, arg GetQuestionnaireParams) (GetQuestionnaireRow, error) {
	row := q.db.QueryRow(ctx, getQuestionnaire, arg.ID, arg.HospitalID)
	var i GetQuestionnaireRow
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.VersionID,
		&i.VersionNo,
		&i.Status,
		&i.UpdatedAt,
		&i.UpdatedByName,
	)
	return i, err
}

const hasNonDraftVersion = `-- name: HasNonDraftVersion :one
SELECT EXISTS (
    SELECT 1 FROM questionnaire_versions WHERE questionnaire_id = $1 AND status <> 'draft'
)
`

func (q *Queries) HasNonDraftVersion(ctx context.Context, questionnaireID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasNonDraftVersion, questionnaireID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listQuestionnaires = `-- name: ListQuestionnaires :many

SELECT q.id, q.name, q.description, q.created_by, q.created_at,
       creator.name AS created_by_name,
       v.version_no, v.status, v.updated_at,
       editor.name AS updated_by_name,
       count(*) OVER () AS total
FROM questionnaires q
JOIN users creator ON creator.id = q.created_by
JOIN LATERAL (
    SELECT id, questionnaire_id, version_no, status, updated_by, updated_at FROM questionnaire_versions qv
    WHERE qv.questionnaire_id = q.id
    ORDER BY qv.version_no DESC LIMIT 1
) v ON true
JOIN users editor ON editor.id = v.updated_by
WHERE q.hospital_id = $1
  AND ($2::text = ''
       OR q.name ILIKE '%' || $2 || '%'
       OR q.description ILIKE '%' || $2 || '%')
ORDER BY v.updated_at DESC, q.name
LIMIT $4 OFFSET $3
`

type ListQuestionnairesParams struct {
	HospitalID uuid.UUID `json:"hospitalId"`
	Search     string    `json:"search"`
	PageOffset int32     `json:"pageOffset"`
	PageSize   int32     `json:"pageSize"`
}

type ListQuestionnairesRow struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	CreatedBy     uuid.UUID `json:"createdBy"`
	CreatedAt     time.Time `json:"createdAt"`
	CreatedByName string    `json:"createdByName"`
	VersionNo     int32     `json:"versionNo"`
	Status        string    `json:"status"`
	UpdatedAt     time.Time `json:"updatedAt"`
	UpdatedByName string    `json:"updatedByName"`
	Total         int64     `json:"total"`
}

// A questionnaire shows its latest version: the draft if there is one, else the last published.
func (q *Queries) ListQuestionnaires(ctx context.Context, arg ListQuestionnairesParams) ([]ListQuestionnairesRow, error) {
	rows, err := q.db.Query(ctx, listQuestionnaires,
		arg.HospitalID,
		arg.Search,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuestionnairesRow{}
	for rows.Next() {
		var i ListQuestionnairesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CreatedByName,
			&i.VersionNo,
			&i.Status,
			&i.UpdatedAt,
			&i.UpdatedByName,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockHospitalQuestionnaires = `-- name: LockHospitalQuestionnaires :exec
SELECT pg_advisory_xact_lock(hashtext($1::uuid::text))
`

// Serialises creates in one hospital so the unique-draft-name check can't race.
func (q *Queries) LockHospitalQuestionnaires(ctx context.Context, hospitalID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockHospitalQuestionnaires, hospitalID)
	return err
}

const publishVersion = `-- name: PublishVersion :one
WITH pub AS (
    UPDATE questionnaire_versions qv
    SET status = 'published', updated_by = $1, updated_at = now()
    WHERE qv.id = $2 AND qv.status = 'draft'
    RETURNING qv.questionnaire_id
), retired AS (
    UPDATE questionnaire_versions
    SET status = 'retired'
    WHERE questionnaire_id IN (SELECT questionnaire_id FROM pub) AND status = 'published'
)
SELECT count(*) FROM pub
`

type PublishVersionParams struct {
	UpdatedBy uuid.UUID `json:"updatedBy"`
	VersionID uuid.UUID `json:"versionId"`
}

// Publishes the draft and retires the version published before it (LCY-01), in one statement.
// Returns 0 when the version is no longer a draft.
func (q *Queries) PublishVersion(ctx context.Context, arg PublishVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, publishVersion, arg.UpdatedBy, arg.VersionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const touchVersion = `-- name: TouchVersion :exec
UPDATE questionnaire_versions SET updated_by = $2, updated_at = now() WHERE id = $1
`

type TouchVersionParams struct {
	ID        uuid.UUID `json:"id"`
	UpdatedBy uuid.UUID `json:"updatedBy"`
}

func (q *Queries) TouchVersion(ctx context.Context, arg TouchVersionParams) error {
	_, err := q.db.Exec(ctx, touchVersion, arg.ID, arg.UpdatedBy)
	return err
}
