// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPatientSession = `-- name: CreatePatientSession :exec
INSERT INTO sessions (id_hash, episode_id, expires_at)
VALUES ($1, $2::uuid, now() + make_interval(secs => $3::float8))
`

type CreatePatientSessionParams struct {
	IDHash        []byte    `json:"idHash"`
	EpisodeID     uuid.UUID `json:"episodeId"`
	MaxAgeSeconds float64   `json:"maxAgeSeconds"`
}

func (q *Queries) CreatePatientSession(ctx context.Context, arg CreatePatientSessionParams) error {
	_, err := q.db.Exec(ctx, createPatientSession, arg.IDHash, arg.EpisodeID, arg.MaxAgeSeconds)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id_hash, user_id, expires_at)
VALUES ($1, $2::uuid, now() + make_interval(secs => $3::float8))
`

type CreateSessionParams struct {
	IDHash        []byte    `json:"idHash"`
	UserID        uuid.UUID `json:"userId"`
	MaxAgeSeconds float64   `json:"maxAgeSeconds"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.IDHash, arg.UserID, arg.MaxAgeSeconds)
	return err
}

const deleteEpisodeSessions = `-- name: DeleteEpisodeSessions :exec
DELETE FROM sessions WHERE episode_id = $1
`

// Signs out every patient session of an episode, e.g. when its link is replaced.
func (q *Queries) DeleteEpisodeSessions(ctx context.Context, episodeID uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, deleteEpisodeSessions, episodeID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, idHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, idHash)
	return err
}

const getPatientSession = `-- name: GetPatientSession :one
SELECT e.id AS episode_id, s.last_seen_at
FROM sessions s
JOIN episodes e ON e.id = s.episode_id
WHERE s.id_hash = $1
  AND s.expires_at > now()
  AND s.last_seen_at > now() - make_interval(secs => $2::float8)
`

type GetPatientSessionParams struct {
	IDHash      []byte  `json:"idHash"`
	IdleSeconds float64 `json:"idleSeconds"`
}

type GetPatientSessionRow struct {
	EpisodeID  uuid.UUID `json:"episodeId"`
	LastSeenAt time.Time `json:"lastSeenAt"`
}

// A live patient session: before its expiry, and used within the idle limit.
func (q *Queries) GetPatientSession(ctx context.Context, arg GetPatientSessionParams) (GetPatientSessionRow, error) {
	row := q.db.QueryRow(ctx, getPatientSession, arg.IDHash, arg.IdleSeconds)
	var i GetPatientSessionRow
	err := row.Scan(&i.EpisodeID, &i.LastSeenAt)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT u.id AS user_id, u.name, s.last_seen_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.id_hash = $1
  AND s.expires_at > now()
  AND s.last_seen_at > now() - make_interval(secs => $2::float8)
`

type GetSessionParams struct {
	IDHash      []byte  `json:"idHash"`
	IdleSeconds float64 `json:"idleSeconds"`
}

type GetSessionRow struct {
	UserID     uuid.UUID `json:"userId"`
	Name       string    `json:"name"`
	LastSeenAt time.Time `json:"lastSeenAt"`
}

// A live staff session: before its expiry, and used within the idle limit. (A patient
// session has no user, so the join leaves it out.)
func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, arg.IDHash, arg.IdleSeconds)
	var i GetSessionRow
	err := row.Scan(&i.UserID, &i.Name, &i.LastSeenAt)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now() WHERE id_hash = $1
`

func (q *Queries) TouchSession(ctx context.Context, idHash []byte) error {
	_, err := q.db.Exec(ctx, touchSession, idHash)
	return err
}
