// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getUser = `-- name: GetUser :one
SELECT id, name, email FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const listMemberships = `-- name: ListMemberships :many
SELECT m.hospital_id, h.name AS hospital_name, m.role
FROM memberships m
JOIN hospitals h ON h.id = m.hospital_id
WHERE m.user_id = $1
ORDER BY h.name, m.role
`

type ListMembershipsRow struct {
	HospitalID   uuid.UUID `json:"hospitalId"`
	HospitalName string    `json:"hospitalName"`
	Role         string    `json:"role"`
}

func (q *Queries) ListMemberships(ctx context.Context, userID uuid.UUID) ([]ListMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsRow{}
	for rows.Next() {
		var i ListMembershipsRow
		if err := rows.Scan(&i.HospitalID, &i.HospitalName, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesInHospital = `-- name: ListRolesInHospital :many
SELECT role FROM memberships WHERE user_id = $1 AND hospital_id = $2
`

type ListRolesInHospitalParams struct {
	UserID     uuid.UUID `json:"userId"`
	HospitalID uuid.UUID `json:"hospitalId"`
}

func (q *Queries) ListRolesInHospital(ctx context.Context, arg ListRolesInHospitalParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listRolesInHospital, arg.UserID, arg.HospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email FROM users ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
